### ISSUE TITLE
No longer need quotes in gather

### ISSUE THREAD

**Issue by itcarroll** [SESYNC-ci/census-data-manipulation-in-R-lesson#2]
... weird.

**Comment by khondula** [comment]
may be related to this: https://rlang.r-lib.org/reference/quasiquotation.html

> This argument is passed by expression and supports quasiquotation (you can unquote strings and symbols). The name is captured from the expression with rlang::ensym() (note that this kind of interface where symbols do not represent actual objects is now discouraged in the tidyverse; we support it here for backward compatibility).

**Comment by qdread** [comment]
I would argue that we should replace `gather` and `spread` in this lesson with the new versions `pivot_longer` and `pivot_wider`. The pivot functions arguably have more sensical syntax.

**Comment by qdread** [comment]
Updated to the `pivot` functions, see [commit](https://github.com/SESYNC-ci/census-data-manipulation-in-R-lesson/commit/66231a0287dd907614619197b2e755c76c324e22)
